project:
  type: website

website:
  title: "simple_quarto_website"
  sidebar:
    contents:
      - href: index.qmd
        text: About me
      - href: Code.qmd
        text: Code
      - href: Data.qmd
        text: Data
      - href: Introduction.qmd
        text: Introduction
      - href: Data Gathering.qmd
        text: Data Gathering
      - href: Data Exploration.qmd
        text: Data Exploration
      - href: Clustering.qmd
        text: Clustering
      - href: Dimensionality Reduction.qmd
        text: Dimensionality Reduction
      - href: Decision Trees.qmd
        text: Decision Trees
      - href: ARM.qmd
        text: ARM
      - href: Conclusions.qmd
        text: Conclusions
    

format:
  html:
    theme: cosmo
    toc: true



